version: '3.3'

services:
  db:
    image: postgres

    restart: always
    environment:
      POSTGRES_DB: stepan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass
    volumes:
      - /var/lib/postgresql
    ports:
      - "6666:5432"